// css id/class selector names

const ANCHOR = {
  GLOBAL_BLUR_CLASS: 'GLOBAL_BLUR_CLASS',
  GLOBAL_HEADER_ID: 'GLOBAL_HEADER_ID',
  GLOBAL_TABBER_ID: 'GLOBAL_TABBER_ID',

  COMMENTS_ID: 'COMMENTS_ID',
}

export default ANCHOR
