const EVENT = {
  // every time when session come back
  SESSTION_ROUTINE: 'SESSTION_ROUTINE',
  LOGIN_PANEL: 'LOGIN_PANEL',
  LOGIN: 'LOGIN',
  // error
  ERR_RESCUE: 'ERR_RESCUE',

  LOGOUT: 'LOGOUT',
  // preview
  PREVIEW_OPEN: 'PREVIEW_OPEN',
  PREVIEW_CLOSE: 'PREVIEW_CLOSE',
  PREVIEW_CLOSED: 'PREVIEW_CLOSED',
  // new end
  USER_LISTER_OPEN: 'USER_LISTER_OPEN',
  CALL_CASHIER: 'CALL_CASHIER',

  // refresh
  REFRESH_COMMUNITIES: 'REFRESH_COMMUNITIES',
  REFRESH_POSTS: 'REFRESH_POSTS',
  REFRESH_REPOS: 'REFRESH_REPOS',
  REFRESH_JOBS: 'REFRESH_JOBS',
  REFRESH_VIDEOS: 'REFRESH_VIDEOS',
  REFRESH_REACTIONS: 'REFRESH_REACTIONS',
  // sync repo
  SYNC_REPO: 'SYNC_REPO',

  // route change
  COMMUNITY_CHANGE: 'COMMUNITY_CHANGE',
  TABBER_CHANGE: 'TABBER_CHANGE',
  // Draft editor
  DRAFT_INSERT_SNIPPET: 'DRAFT_INSERT_SNIPPET',

  // favorites
  SET_FAVORITE_CONTENT: 'SET_FAVORITE_CONTENT',
  // customization
  SET_C11N: 'SET_C11N',
  // bills
  NEW_BILLS: 'NEW_BILLS',

  // upload
  UPLOAD_IMG_START: 'UPLOAD_IMG_START',
  UPLOAD_IMG_FINISH: 'UPLOAD_IMG_FINISH',

  // doramon
  QUERY_DORAMON: 'QUERY_DORAMON',

  // set/unset community
  COMMUNITY_MIRROR: 'COMMUNITY_MIRROR',

  // shortcut for social modal
  SOCIAL_MODAL: 'SOCIAL_MODAL',
  //
  C11N_DENSITY_CHANGE: 'C11N_DENSITY_CHANGE',
}

export default EVENT
