const FILTER = {
  // when
  TODAY: 'TODAY',
  THIS_WEEK: 'THIS_WEEK',
  THIS_MONTH: 'THIS_MONTH',
  THIS_YEAR: 'THIS_YEAR',

  // sort
  MOST_VIEWS: 'MOST_VIEWS',
  MOST_STARS: 'MOST_STARS',
  MOST_FAVORITES: 'MOST_FAVORITES',
  MOST_COMMENTS: 'MOST_COMMENTS',

  ASC_INSERTED: 'ASC_INSERTED',
  DESC_INSERTED: 'DESC_INSERTED',
  MOST_LIKES: 'MOST_LIKES',
  MOST_DISLIKES: 'MOST_DISLIKES',

  MOST_GITHUB_STAR: 'MOST_GITHUB_STAR',
  MOST_GITHUB_FORK: 'MOST_GITHUB_FORK',
  MOST_GITHUB_WATCH: 'MOST_GITHUB_WATCH',

  // length
  MOST_WORDS: 'MOST_WORDS',
  LEAST_WORDS: 'LEAST_WORDS',

  // READ
  READ: 'TRUE',
  UNREAD: 'FLASE',
  ALL: 'ALL',
}

export default FILTER
