const GUIDE = {
  PREVIEW: 'PREVIEW',
  DEFAULT: 'DEFAULT',
  FAME_PEOPLE: 'FAME_PEOPLE',
  IMAGE: 'IMAGE',
  SNIPPETS_LIST: 'SNIPPETS_LIST',
  SNIPPETS_MASONRY: 'SNIPPETS_MASONRY',
}

export default GUIDE
