// NOTE:  the value is mapping to @/utils/media's key
// so do not change to lowercase etc...
const METRIC = {
  COMMUNITY: 'COMMUNITY',
  USER: 'USER',
  ARTICLE: 'ARTICLE',
  WORKS_ARTICLE: 'WORKS_ARTICLE',
  WORKS: 'WORKS',

  DISCOVERY: 'DISCOVERY',
  SPONSOR: 'SPONSOR',
  FRIENDS: 'FRIENDS',
  SUBSCRIBE: 'SUBSCRIBE',
  MEETUPS: 'MEETUPS',

  TRENDING: 'TRENDING',
  COOL_GUIDE: 'COOL_GUIDE',
  HAVE_A_DRINK: 'HAVE_A_DRINK',
  RECIPES: 'RECIPES',

  MEMBERSHIP: 'MEMBERSHIP',

  WORKS_EDITOR: 'WORKS_EDITOR',
  COMMUNITY_EDITOR: 'COMMUNITY_EDITOR',
  ARTICLE_EDITOR: 'ARTICLE_EDITOR',

  HELP_CENTER: 'HELP_CENTER',
}

export default METRIC
