export const PAYMENT_USAGE = {
  SENIOR: 'SENIOR',
  GIRLS_CODE_TOO_PLAN: 'GirlsCodeTooPlan',
  DONATE: 'DONATE',
  SPONSOR: 'SPONSOR',
}

export const PAYMENT_METHOD = {
  ALIPAY: 'ALIPAY',
  WECHAT: 'WECHAT',
}
