// type

const TYPE = {
  CUR_THEME: 'cur_theme',
  GLOBAL_BLUR_CLASS: 'GLOBAL_BLUR_CLASS',
  APP_HEADER_ID: 'APP_HEADER_ID',
  APP_TABBER_ID: 'APP_TABBER_ID',

  CHEATSHEET_ROOT_PAGE: 'CHEATSHEET_ROOT_PAGE',
  COMMUNITIES_ROOT_PAGE: 'COMMUNITIES_ROOT_PAGE',
  COMMUNITY_PAGE: 'COMMUNITY_PAGE',
  POST_PAGE: 'POST_PAGE',
  MEETUPS_ROOT_PAGE: 'MEETUPS_ROOT_PAGE',

  POST: 'POST',
  JOB: 'JOB',
  REPO: 'REPO',
  VIDEO: 'VIDEO',
  // actions
  FAVORITE: 'FAVORITE',
  STAR: 'STAR',
  WATCH: 'WATCH',
  REACTION: 'reaction',
  UNDO_REACTION: 'undoReaction',

  USER_LISTER_FAVORITES: 'USER_LISTER_FAVORITES',
  USER_LISTER_STARS: 'USER_LISTER_STARS',
  USER_LISTER_COMMUNITY_EDITORS: 'USER_LISTER_COMMUNITY_EDITORS',
  USER_LISTER_COMMUNITY_SUBSCRIBERS: 'USER_LISTER_COMMUNITY_SUBSCRIBERS',

  USER_LISTER_FOLLOWINGS: 'USER_LISTER_FOLLOWINGS',
  USER_LISTER_FOLLOWERS: 'USER_LISTER_FOLLOWERS',

  // drawer types
  DRAWER: {
    ACCOUNT_VIEW: 'ACCOUNT_VIEW',
    USER_VIEW: 'USER_VIEW',
    ACCOUNT_EDIT: 'ACCOUNT_EDIT',

    MAILS_VIEW: 'MAILS_VIEW',
    ROOT_STORE: 'ROOT_STORE',

    POST_VIEW: 'POST_VIEW',
    POST_CREATE: 'POST_CREATE',
    POST_EDIT: 'POST_EDIT',

    JOB_VIEW: 'JOB_VIEW',
    JOB_CREATE: 'JOB_CREATE',
    JOB_EDIT: 'JOB_EDIT',

    REPO_VIEW: 'REPO_VIEW',
    REPO_CREATE: 'REPO_CREATE',

    VIDEO_VIEW: 'VIDEO_VIEW',
    VIDEO_CREATE: 'VIDEO_CREATE',
    VIDEO_EDIT: 'VIDEO_EDIT',

    // c11n settings
    C11N_SETTINGS: 'C11N_SETTINGS',
    // header navi menu in mobile mode
    MOBILE_NAVI_MENU: 'MOBILE_NAVI_MENU',

    // modeline
    MODELINE_MENU: 'MODELINE_MENU',
  },

  // PAGE STATE
  LOADING: 'LOADING',
  NOT_FOUND: 'NOT_FOUND',
  RESULT: 'RESULT',
  RESULT_EMPTY: 'RESULT_EMPTY',
  // filters
  ASC_INSERTED: 'ASC_INSERTED',
  DESC_INSERTED: 'DESC_INSERTED',
  MOST_LIKES: 'MOST_LIKES',
  MOST_DISLIKES: 'MOST_DISLIKES',
}

export default TYPE
