// type

const TYPE = {
  CUR_THEME: 'cur_theme',

  CHEATSHEET_ROOT_PAGE: 'CHEATSHEET_ROOT_PAGE',
  COMMUNITIES_ROOT_PAGE: 'COMMUNITIES_ROOT_PAGE',
  COMMUNITY_PAGE: 'COMMUNITY_PAGE',
  POST_PAGE: 'POST_PAGE',
  MEETUPS_ROOT_PAGE: 'MEETUPS_ROOT_PAGE',

  POST: 'POST',
  JOB: 'JOB',
  REPO: 'REPO',
  // actions
  FAVORITE: 'FAVORITE',
  STAR: 'STAR',
  WATCH: 'WATCH',
  REACTION: 'reaction',
  UNDO_REACTION: 'undoReaction',

  USER_LISTER_FAVORITES: 'USER_LISTER_FAVORITES',
  USER_LISTER_STARS: 'USER_LISTER_STARS',
  USER_LISTER_COMMUNITY_EDITORS: 'USER_LISTER_COMMUNITY_EDITORS',
  USER_LISTER_COMMUNITY_SUBSCRIBERS: 'USER_LISTER_COMMUNITY_SUBSCRIBERS',

  USER_LISTER_FOLLOWINGS: 'USER_LISTER_FOLLOWINGS',
  USER_LISTER_FOLLOWERS: 'USER_LISTER_FOLLOWERS',

  // drawer types
  DRAWER: {
    ACCOUNT_VIEW: 'ACCOUNT_VIEW',
    USER_VIEW: 'USER_VIEW',
    ACCOUNT_EDIT: 'ACCOUNT_EDIT',

    MAILS_VIEW: 'MAILS_VIEW',

    POST_VIEW: 'POST_VIEW',
    POST_CREATE: 'POST_CREATE',
    POST_EDIT: 'POST_EDIT',

    JOB_VIEW: 'JOB_VIEW',
    JOB_CREATE: 'JOB_CREATE',
    JOB_EDIT: 'JOB_EDIT',

    REPO_VIEW: 'REPO_VIEW',
    REPO_CREATE: 'REPO_CREATE',

    // c11n settings
    C11N_SETTINGS: 'C11N_SETTINGS',

    // modeline
    MODELINE_MENU: 'MODELINE_MENU',
  },

  REPORT: {
    ARTICLE: 'ARTICLE',
    USER: 'USER',
    COMMENT: 'COMMENT',
    COMMUNITY: 'COMMUNITY',
  },

  // modeline menu type
  MM_TYPE: {
    GLOBAL_MENU: 'global_menu',
    COMMUNITY: 'community',
    FILTER: 'filter',
    DISCOVER: 'discover',
    PUBLISH: 'publish',
    SEARCH: 'search',
    MORE: 'more',
  },
  // PAGE STATE
  LOADING: 'LOADING',
  NOT_FOUND: 'NOT_FOUND',
  RESULT: 'RESULT',
  RESULT_EMPTY: 'RESULT_EMPTY',
  // filters
  ASC_INSERTED: 'ASC_INSERTED',
  DESC_INSERTED: 'DESC_INSERTED',
  MOST_LIKES: 'MOST_LIKES',
  MOST_DISLIKES: 'MOST_DISLIKES',
}

export default TYPE
