// type

const TYPE = {
  APP_HEADER_ID: 'APP_HEADER_ID',
  APP_TABBER_ID: 'APP_TABBER_ID',

  CHEATSHEET_ROOT_PAGE: 'CHEATSHEET_ROOT_PAGE',
  COMMUNITIES_ROOT_PAGE: 'COMMUNITIES_ROOT_PAGE',
  COMMUNITY_PAGE: 'COMMUNITY_PAGE',
  POST_PAGE: 'POST_PAGE',
  ACTIVITIES_ROOT_PAGE: 'ACTIVITIES_ROOT_PAGE',

  POST: 'POST',
  JOB: 'JOB',
  REPO: 'REPO',
  VIDEO: 'VIDEO',
  // actions
  FAVORITE: 'FAVORITE',
  STAR: 'STAR',
  WATCH: 'WATCH',
  REACTION: 'reaction',
  UNDO_REACTION: 'undoReaction',

  USER_LISTER_FAVORITES: 'USER_LISTER_FAVORITES',
  USER_LISTER_STARS: 'USER_LISTER_STARS',
  USER_LISTER_COMMUNITY_EDITORS: 'USER_LISTER_COMMUNITY_EDITORS',
  USER_LISTER_COMMUNITY_SUBSCRIBERS: 'USER_LISTER_COMMUNITY_SUBSCRIBERS',

  USER_LISTER_FOLLOWINGS: 'USER_LISTER_FOLLOWINGS',
  USER_LISTER_FOLLOWERS: 'USER_LISTER_FOLLOWERS',

  // preview
  PREVIEW_ACCOUNT_VIEW: 'PREVIEW_ACCOUNT_VIEW',
  PREVIEW_USER_VIEW: 'PREVIEW_USER_VIEW',
  PREVIEW_ACCOUNT_EDIT: 'PREVIEW_ACCOUNT_EDIT',

  PREVIEW_MAILS_VIEW: 'PREVIEW_MAILS_VIEW',
  PREVIEW_ROOT_STORE: 'PREVIEW_ROOT_STORE',

  PREVIEW_POST_VIEW: 'PREVIEW_POST_VIEW',
  PREVIEW_POST_CREATE: 'PREVIEW_POST_CREATE',
  PREVIEW_POST_EDIT: 'PREVIEW_POST_EDIT',

  PREVIEW_JOB_VIEW: 'PREVIEW_JOB_VIEW',
  PREVIEW_JOB_CREATE: 'PREVIEW_JOB_CREATE',
  PREVIEW_JOB_EDIT: 'PREVIEW_JOB_EDIT',

  PREVIEW_REPO_VIEW: 'PREVIEW_REPO_VIEW',
  PREVIEW_REPO_CREATE: 'PREVIEW_REPO_CREATE',

  PREVIEW_VIDEO_VIEW: 'PREVIEW_VIDEO_VIEW',
  PREVIEW_VIDEO_CREATE: 'PREVIEW_VIDEO_CREATE',
  PREVIEW_VIDEO_EDIT: 'PREVIEW_VIDEO_EDIT',

  // PAGE STATE
  LOADING: 'LOADING',
  NOT_FOUND: 'NOT_FOUND',
  RESULT: 'RESULT',
  RESULT_EMPTY: 'RESULT_EMPTY',
  // filters
  ASC_INSERTED: 'ASC_INSERTED',
  DESC_INSERTED: 'DESC_INSERTED',
  MOST_LIKES: 'MOST_LIKES',
  MOST_DISLIKES: 'MOST_DISLIKES',
}

export default TYPE
