import { ICON_CMD } from '@/config'

const demo = [
  {
    id: '1000',
    icon: `${ICON_CMD}/drink/it-cold.svg`,
    title: '细节魔鬼',
    total: '224',
    desc: '各种产品中的彩蛋和用心细节',
    updatedAt: '3天前',
  },
  {
    id: '0',
    icon: `${ICON_CMD}/drink/it-cold.svg`,
    title: 'IT 冷知识',
    total: '224',
    desc: '看见一个算命大师，我刚坐下他就问我，你算什么东西?',
    updatedAt: '3天前',
  },
  {
    id: '31',
    icon: `${ICON_CMD}/drink/driver.svg`,
    title: '段子可视化',
    total: '224',
    desc: '看见一个算命大师，我刚坐下他就问我，你算什么东西?',
    updatedAt: '3天前',
  },
  {
    id: '1',
    icon: `${ICON_CMD}/drink/number.svg`,
    title: '数据酷',
    total: '224',
    desc: '看见一个算命大师，我刚坐下他就问我，你算什么东西?',
    updatedAt: '3天前',
    active: true,
  },
  {
    id: '12',
    icon: `${ICON_CMD}/drink/naming.svg`,
    title: '传神命名',
    total: '224',
    desc: '业内、工作中那些优雅传神的命名',
    updatedAt: '3天前',
  },
  {
    id: '2',
    icon: `${ICON_CMD}/drink/chicken.svg`,
    title: '毒鸡汤',
    total: '224',
    desc: '看见一个算命大师，我刚坐下他就问我，你算什么东西?',
    updatedAt: '3天前',
  },
  {
    id: '3',
    icon: `${ICON_CMD}/drink/muscle.svg`,
    title: '励志柴油',
    total: '224',
    desc: '看见一个算命大师，我刚坐下他就问我，你算什么东西?',
    updatedAt: '3天前',
  },
  {
    id: '32',
    icon: `${ICON_CMD}/drink/zhihu.svg`,
    title: 'Oh My Lang',
    total: '224',
    desc: '你所知的小众编程语言特性',
    updatedAt: '3天前',
  },
  {
    id: '4',
    icon: `${ICON_CMD}/drink/smile.svg`,
    title: '晒工台',
    total: '224',
    desc: '看见一个算命大师，我刚坐下他就问我，你算什么东西?',
    updatedAt: '3天前',
  },
  {
    id: '5',
    icon: `${ICON_CMD}/drink/brain.svg`,
    title: 'APP 下架奇谈',
    total: '224',
    desc: '看见一个算命大师，我刚坐下他就问我，你算什么东西?',
    updatedAt: '3天前',
  },
  {
    id: '6',
    icon: `${ICON_CMD}/drink/chicken.svg`,
    title: '我的编辑器',
    total: '224',
    desc: '看见一个算命大师，我刚坐下他就问我，你算什么东西?',
    updatedAt: '3天前',
  },
  {
    id: '7',
    icon: `${ICON_CMD}/drink/rap.svg`,
    title: '令人作呕',
    total: '22',
    desc: '太阳不起我不起 老子就是了不起',
    updatedAt: '3天前',
  },
  {
    id: '8',
    icon: `${ICON_CMD}/drink/rap.svg`,
    title: '言论收集簿',
    total: '22',
    desc: '太阳不起我不起 老子就是了不起',
    updatedAt: '3天前',
  },
  {
    id: '9',
    icon: `${ICON_CMD}/drink/rap.svg`,
    title: '交个朋友',
    total: '22',
    desc: '不是直播间，是化学实验室。',
    updatedAt: '3天前',
  },
]

export default demo
