export {
  DEFAULT_THEME,
  SENINOR_AMOUNT_THRESHOLD,
  SPONSOR_AMOUNT_THRESHOLD,
  PAGE_SIZE,
  WORD_LIMIT,
  TAG_COLORS,
  TAG_COLOR_ORDER,
} from './general'

export {
  GRAPHQL_ENDPOINT,
  ISSUE_ADDR,
  GITHUB_WEB_ADDR,
  GITHUB_SERVER_ADDR,
  GITHUB_ME,
  GITHUB_CPS_TEAM,
  MENTION_USER_ADDR,
  COMMUNITY_WIKI,
  DEFAULT_USER_AVATAR,
} from './endpoint'

export { ASSETS_ENDPOINT, ICON_BASE, ICON_CMD, DEFAULT_ICON } from './assets'

export { default as LABEL_POOL } from './label_pool'
