export const ERR = {
  CRAPHQL: 'CRAPHQL',
  PARSE_CHEATSHEET_MD: 'PARSE_CHEATSHEET_MD',
  NETWORK: 'NETWORK',
  NOT_FOUND: 'NOT_FOUND',
  TIMEOUT: 'TIMEOUT',
}

export const EVENT = {
  LOGIN_PANEL: 'LOGIN_PANEL',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  PREVIEW: 'PREVIEW',
  PREVIEW_CLOSE: 'PREVIEW_CLOSE',
  PREVIEW_POST: 'PREVIEW_POST',
  NAV_EDIT: 'NAV_EDIT',
  NAV_CREATE_POST: 'NAV_CREATE_POST',
  REFRESH_POSTS: 'REFRESH_POSTS',
}

export const TYPE = {
  POST: 'POST',
  JOB: 'JOB',
  FAVORITE: 'FAVORITE',
  STAR: 'STAR',
  WATCH: 'WATCH',
  REACTION: 'reaction',
  UNDO_REACTION: 'undoReaction',
  POST_PREVIEW_VIEW: 'POST_PREVIEW_VIEW',
  ACCOUNT_PREVIEW_VIEW: 'ACCOUNT_PREVIEW_VIEW',
  PREVIEW_ROOT_STORE: 'PREVIEW_ROOT_STORE',
  PREVIEW_CREATE_POST: 'PREVIEW_CREATE_POST',
}
