export type TGALLERY_DEFAULT = 'default'
export type TGALLERY_LIST = 'list'
export type TGALLERY_MASONRY_COLUMN = 'masonry_column'
export type TGALLERY_MAIN_COLUMN = 'main_column'
export type TGALLERY_TWO_COLUMN = 'two_column'
export type TGALLERY_THREE_COLUMN = 'three_column'
export type TGALLERY_TEXT_ONLY = 'text_only'
export type TGALLERY_TEXT_WITH_IMAGE = 'text_with_image'
